# Generated by Django 3.0.8 on 2020-07-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_experience_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(help_text='Prénom', max_length=50)),
                ('lastname', models.CharField(help_text='Nom', max_length=50)),
                ('companyname', models.CharField(blank=True, help_text="Nom de l'entreprise", max_length=100)),
                ('mail', models.CharField(blank=True, help_text='Email', max_length=100)),
                ('message', models.TextField(help_text='Message de recommandation')),
                ('date', models.DateField(help_text='Date du message')),
                ('verified', models.BooleanField(help_text='Non affichée / Affichée')),
            ],
        ),
    ]
