# Generated by Django 3.0.14 on 2023-07-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='inline',
            field=models.BooleanField(default=False, help_text='Afficher en ligne / Non affichée'),
        ),
        migrations.AlterField(
            model_name='study',
            name='description',
            field=models.TextField(blank=True, help_text='Description de la formation', null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='duration',
            field=models.CharField(blank=True, help_text='Durée de la formation', max_length=30, null=True),
        ),
    ]
