# Generated by Django 3.0.14 on 2023-07-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('WEB', 'web'), ('DEVOPS', 'devops'), ('AI', 'ai')], max_length=20),
        ),
    ]
