# Generated by Django 3.0.14 on 2023-07-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230724_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('WEB', 'web'), ('DEVOPS', 'devops'), ('AI', 'ai'), ('PROJECT', 'project')], max_length=20),
        ),
    ]
